"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = __importDefault(require("express"));
var cors_1 = __importDefault(require("cors"));
var body_parser_1 = __importDefault(require("body-parser"));
var router_1 = __importDefault(require("./router"));
var path_1 = __importDefault(require("path"));
var app = (0, express_1.default)();
app.use(express_1.default.json());
app.use(body_parser_1.default.urlencoded({ extended: true }));
app.use(body_parser_1.default.json());
app.use((0, cors_1.default)({ origin: "*" }));
var imagesPath = path_1.default.resolve(__dirname, "..", "..", "kepek");
var imagesPathFallback = path_1.default.resolve(__dirname, "kepek");
app.use("/kepek", express_1.default.static(imagesPath));
app.use("/kepek", express_1.default.static(imagesPathFallback));
app.use("/", router_1.default);
exports.default = app;
