import { Request, Response } from "express";
export declare const run: (_req: Request, res: Response) => void;
export declare const registerUser: (req: Request, res: Response) => Promise<void>;
export declare const loginUser: (req: Request, res: Response) => Promise<void>;
export declare const userSettings: (req: Request, res: Response) => Promise<void>;
export declare const getItemsByCategories: (req: Request, res: Response) => Promise<void>;
export declare const addItem: (req: Request, res: Response) => Promise<void>;
export declare const updateItem: (req: Request, res: Response) => Promise<void>;
export declare const deleteItem: (req: Request, res: Response) => Promise<void>;
export declare const getCategories: (_req: Request, res: Response) => Promise<void>;
export declare const addCategory: (req: Request, res: Response) => Promise<void>;
export declare const deleteCategory: (req: Request, res: Response) => Promise<void>;
export declare const getUserRole: (req: Request, res: Response) => Promise<void>;
