"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var controller_1 = require("./controller");
var router = (0, express_1.Router)();
router.get("/", router);
router.get("/", controller_1.run);
router.post("/register", controller_1.registerUser);
router.post("/login", controller_1.loginUser);
exports.default = router;
